version: "3.9"

services:
  db:
    platform: linux/x86_64
    image: postgres:latest
    container_name: container-db
    environment:
      - "POSTGRES_DB=test"
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=test"
    ports:
      - "5432:5432"