#version: "3.7"
#
#services:
#
#  database:
#    container_name: postgre
#    image: postgres:latest
#    restart: always
#    platform: linux/x86_64
#    ports:
#      - "5432:5432"
#    environment:
#      - "POSTGRES_DB=test"
#      - "POSTGRES_USER=test"
#      - "POSTGRES_PASSWORD=test"
#
#  cache:
#    container_name: redis
#    image: redis:alpine
#    ports:
#      - "6379:16379"
#

version: "3.9"

services:
  db:
    platform: linux/x86_64
    image: mysql:8
    container_name: container-db
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=true"
      - "MYSQL_DATABASE=test"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=test"
    ports:
      - "3310:3306"