spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3310/test?useSSL=false&allowPublicKeyRetrieval=true
#    username: test
#    password: test
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create #create-drop....
  data:
    redis:
      port: 16379
      host: bubaum.dev
      password: NdTmsXFaYuT4H7x
  cache:
    type: redis
logging:
  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.boot.autoconfigure: OFF
