spring:
  datasource:
#    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?characterEncoding=UTF-8&serverTimezone=UTC
#    username: ${MYSQL_USERNAME}
#    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://127.0.0.1:3310/test?useSSL=false&allowPublicKeyRetrieval=true
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update #create-drop....
      show-sql: true
  data:
    redis:
      port: 6379
      host: 127.0.0.1
#      username: default
#      password: NdTmsXFaYuT4H7x
  cache:
    type: redis
logging:
  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.boot.autoconfigure: OFF
